import React, { useState } from 'react';
import { Database, ShieldAlert, Sparkles, Terminal, Copy, Check, Play } from 'lucide-react';
import { db } from '../utils/db';

export default function ConnectionModal({ onConnected, onStartDemo }) {
  const [url, setUrl] = useState('');
  const [anonKey, setAnonKey] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [copiedEmployeesSql, setCopiedEmployeesSql] = useState(false);
  const [copiedAppsSql, setCopiedAppsSql] = useState(false);
  const [copiedHistorySql, setCopiedHistorySql] = useState(false);

  const EMPLOYEES_SQL = `CREATE TABLE IF NOT EXISTS tb_employees (
  emp_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  company_name text NOT NULL CHECK (company_name IN ('미래에이비엠', '다원피엠씨', '정다운세상', '다원엔텍')),
  site_name text NOT NULL,
  department text NOT NULL,
  role text NOT NULL,
  phone text NOT NULL,
  email text,
  status text NOT NULL DEFAULT '재직' CHECK (status IN ('재직', '휴직', '퇴사')),
  authority text NOT NULL DEFAULT '일반사용자' CHECK (authority IN ('본사관리자', '현장관리자', '일반사용자')),
  status_reason text,
  status_date text,
  leave_start_date text,
  leave_end_date text,
  hire_date text NOT NULL,
  contract_type text NOT NULL DEFAULT '정규직' CHECK (contract_type IN ('정규직', '계약직')),
  contract_end_date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);`;

  const INTEGRATION_SQL = `CREATE TABLE IF NOT EXISTS tb_apps_integration (
  id text PRIMARY KEY,
  name text NOT NULL,
  auth_type text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  columns text[] NOT NULL,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);`;

  const HISTORY_SQL = `CREATE TABLE IF NOT EXISTS tb_status_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id bigint NOT NULL REFERENCES tb_employees(emp_id) ON DELETE CASCADE,
  name text NOT NULL,
  company_name text NOT NULL,
  previous_status text NOT NULL,
  new_status text NOT NULL,
  status_reason text,
  status_date text NOT NULL,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);`;

  const handleConnect = async (e) => {
    e.preventDefault();
    if (!url || !anonKey) {
      setErrorMsg('Supabase URL과 Anon Key를 모두 입력해 주세요.');
      return;
    }

    setLoading(true);
    setErrorMsg('');

    const res = await db.connect(url, anonKey);
    setLoading(false);

    if (res.success) {
      onConnected();
    } else {
      setErrorMsg(res.error || '연동 실패: URL 및 Anon Key를 다시 확인해 주세요.');
    }
  };

  const handleCopy = (text, setCopied) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#FAFAFA] dark:bg-zinc-950 p-4 font-sans transition-colors duration-200">
      
      {/* Crisp clean card wrapper */}
      <div className="w-full max-w-4xl bg-white dark:bg-zinc-900 border border-zinc-200/70 dark:border-zinc-800/80 rounded-2xl shadow-sm p-6 md:p-8 animate-slide-up relative">
        <div className="flex flex-col lg:flex-row gap-8 items-stretch">
          
          {/* Left Panel: Introduction & Instructions */}
          <div className="flex-1 flex flex-col justify-between text-left">
            <div>
              <div className="flex items-center gap-2 mb-3">
                <img src="/logo.png" className="h-6 w-auto object-contain bg-transparent select-none" alt="Mirae ABM Logo" />
                <span className="text-[10px] font-bold tracking-wider text-zinc-400 dark:text-zinc-500 uppercase font-mono mt-0.5 border-l border-zinc-200 dark:border-zinc-850 pl-2">HR Data Hub</span>
              </div>
              
              <h1 className="text-2xl md:text-3xl font-extrabold text-zinc-900 dark:text-white tracking-tight leading-tight m-0 font-display">
                인사 데이터 통합 마스터 <br />
                <span className="text-[#1B3D8E] dark:text-[#3B66C4]">백오피스 포털</span>
              </h1>
              
              <p className="text-zinc-500 dark:text-zinc-400 text-xs md:text-sm leading-relaxed mt-3.5 max-w-lg">
                본 시스템은 본사 및 전 현장의 인사 정보를 한눈에 감시하고 직관적으로 관리할 뿐만 아니라, 사내/외 다양한 하부 업무용 서비스들과 공통 DB 정보를 선별 연동하도록 지원하는 **보안 인증 마스터 허브**입니다.
              </p>
            </div>

            {/* SQL Guide Widget */}
            <div className="mt-6 border border-zinc-200 dark:border-zinc-800 rounded-2xl bg-zinc-50/50 dark:bg-zinc-950/40 p-4">
              <div className="flex items-center gap-2 text-zinc-700 dark:text-zinc-300 font-bold mb-1.5">
                <Terminal size={14} className="text-[#F39C12]" />
                <span className="text-xs">💡 Supabase 연동 테이블 스키마 가이드</span>
              </div>
              <p className="text-[11px] text-zinc-500 dark:text-zinc-400 mb-3 leading-relaxed">
                실제 Supabase DB 연동을 시작하기 전에 아래 SQL 문을 복사하여 **Supabase SQL Editor**에서 실행해 주시기 바랍니다.
              </p>
              
              <div className="space-y-2">
                {/* Employees SQL Copy */}
                <div className="flex items-center justify-between bg-white dark:bg-zinc-900/60 p-2.5 rounded-xl border border-zinc-150 dark:border-zinc-800 text-left">
                  <div className="truncate pr-4">
                    <span className="text-xs font-mono font-semibold text-zinc-700 dark:text-zinc-300">1. 직원 데이터 테이블 (tb_employees)</span>
                  </div>
                  <button
                    onClick={() => handleCopy(EMPLOYEES_SQL, setCopiedEmployeesSql)}
                    className="flex items-center gap-1 px-2.5 py-1 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-850 dark:hover:bg-zinc-800 text-[10px] font-semibold text-zinc-700 dark:text-zinc-300 rounded-lg border border-zinc-200/60 dark:border-zinc-700/50 cursor-pointer transition-colors"
                  >
                    {copiedEmployeesSql ? (
                      <>
                        <Check size={10} className="text-emerald-500" />
                        <span className="text-emerald-500">복사 완료</span>
                      </>
                    ) : (
                      <>
                        <Copy size={10} />
                        <span>SQL 복사</span>
                      </>
                    )}
                  </button>
                </div>

                {/* Integration App SQL Copy */}
                <div className="flex items-center justify-between bg-white dark:bg-zinc-900/60 p-2.5 rounded-xl border border-zinc-150 dark:border-zinc-800 text-left">
                  <div className="truncate pr-4">
                    <span className="text-xs font-mono font-semibold text-zinc-700 dark:text-zinc-300">2. 연동 앱 관리 테이블 (tb_apps_integration)</span>
                  </div>
                  <button
                    onClick={() => handleCopy(INTEGRATION_SQL, setCopiedAppsSql)}
                    className="flex items-center gap-1 px-2.5 py-1 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-850 dark:hover:bg-zinc-800 text-[10px] font-semibold text-zinc-700 dark:text-zinc-300 rounded-lg border border-zinc-200/60 dark:border-zinc-700/50 cursor-pointer transition-colors"
                  >
                    {copiedAppsSql ? (
                      <>
                        <Check size={10} className="text-emerald-500" />
                        <span className="text-emerald-500">복사 완료</span>
                      </>
                    ) : (
                      <>
                        <Copy size={10} />
                        <span>SQL 복사</span>
                      </>
                    )}
                  </button>
                </div>

                {/* Status History SQL Copy */}
                <div className="flex items-center justify-between bg-white dark:bg-zinc-900/60 p-2.5 rounded-xl border border-zinc-150 dark:border-zinc-800 text-left">
                  <div className="truncate pr-4">
                    <span className="text-xs font-mono font-semibold text-zinc-700 dark:text-zinc-300">3. 인사 변동 이력 테이블 (tb_status_history)</span>
                  </div>
                  <button
                    onClick={() => handleCopy(HISTORY_SQL, setCopiedHistorySql)}
                    className="flex items-center gap-1 px-2.5 py-1 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-850 dark:hover:bg-zinc-800 text-[10px] font-semibold text-zinc-700 dark:text-zinc-300 rounded-lg border border-zinc-200/60 dark:border-zinc-700/50 cursor-pointer transition-colors"
                  >
                    {copiedHistorySql ? (
                      <>
                        <Check size={10} className="text-emerald-500" />
                        <span className="text-emerald-500">복사 완료</span>
                      </>
                    ) : (
                      <>
                        <Copy size={10} />
                        <span>SQL 복사</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Right Panel: Connection form input block */}
          <div className="w-full lg:w-[350px] bg-zinc-50/50 dark:bg-zinc-950/20 border border-zinc-200/60 dark:border-zinc-800/60 rounded-2xl p-5 md:p-6 flex flex-col justify-between">
            <div>
              <div className="text-left mb-5">
                <h3 className="text-sm md:text-base font-bold text-zinc-800 dark:text-white m-0">DB 서버 연동</h3>
                <p className="text-[11px] text-zinc-500 dark:text-zinc-400 mt-1 select-none">
                  Supabase 프로젝트 연동 정보를 등록해 주십시오.
                </p>
              </div>

              <form onSubmit={handleConnect} className="space-y-3.5">
                <div className="text-left">
                  <label className="block text-[10px] font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
                    Supabase Project URL
                  </label>
                  <input
                    type="url"
                    placeholder="https://your-project.supabase.co"
                    value={url}
                    onChange={(e) => setUrl(e.target.value)}
                    className="w-full bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl px-3 py-2 text-xs md:text-sm text-zinc-800 dark:text-white focus:outline-none focus:border-[#1B3D8E] focus:ring-1 focus:ring-[#1B3D8E] font-mono transition-all"
                  />
                </div>

                <div className="text-left">
                  <label className="block text-[10px] font-semibold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider mb-1">
                    Supabase Anon Key
                  </label>
                  <textarea
                    rows="3"
                    placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    value={anonKey}
                    onChange={(e) => setAnonKey(e.target.value)}
                    className="w-full bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl px-3 py-2 text-[11px] text-zinc-800 dark:text-white focus:outline-none focus:border-[#1B3D8E] focus:ring-1 focus:ring-[#1B3D8E] font-mono resize-none transition-all"
                  />
                </div>

                {errorMsg && (
                  <div className="p-3 bg-rose-500/5 border border-rose-500/15 text-rose-600 dark:text-rose-400 rounded-xl flex items-start gap-1.5 text-[11px] leading-normal animate-slide-up text-left">
                    <ShieldAlert size={12} className="shrink-0 mt-0.5" />
                    <span>{errorMsg}</span>
                  </div>
                )}

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-2.5 px-4 bg-gradient-to-r from-[#1B3D8E] to-[#3B66C4] hover:from-[#153173] hover:to-[#2F53A8] text-white font-semibold text-xs md:text-sm rounded-xl cursor-pointer transition-all shadow-sm flex items-center justify-center gap-1.5 disabled:opacity-50"
                >
                  {loading ? (
                    <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>
                  ) : (
                    <>
                      <Database size={14} />
                      <span>실시간 DB 연동</span>
                    </>
                  )}
                </button>
              </form>
            </div>

          </div>
        </div>

        <button
          type="button"
          onClick={onStartDemo}
          className="text-[10px] text-zinc-350 hover:text-zinc-500 dark:text-zinc-700 dark:hover:text-zinc-650 hover:underline absolute bottom-3.5 right-4.5 cursor-pointer transition-colors"
        >
          개발자용 로컬 시뮬레이션 모드
        </button>
      </div>
    </div>
  );
}
